################################################################################
###                           Table of contents
################################################################################
# docker-compose.yml - Docker configuration for all services
# common.yml         - Contains essential configuration for FredBoat and Sentinel
# fredboat.yml       - FredBoat config
# lavalink.yml       - Lavalink config
# quarterdeck.yml    - Quarterdeck config

# **If using Docker Swarm, it's better to use "configs" and "secrets" to store these files**

################################################################################
###                  Selfhosting FredBoat with Docker Swarm
################################################################################
###
### Use a proper text editor like Sublime when editing this file
### Do not use tab characters in this file, only spaces are allowed. Don't add or delete unnecessary spaces.
### More information on correctly formatting yaml files: http://www.yaml.org/start.html
###
### For further information on running FredBoat visit https://fredboat.com/docs/selfhosting or the #selfhosting channel
### on the FredBoat Hangout Discord server: https://discord.gg/cgPFW4q


version: '3.7' # This is not the FredBoat version, do not touch this line.
services:

  ################################################################################
  ##                               Database
  ################################################################################
  db:
    image: fredboat/postgres:latest
    restart: always
    volumes:
        - postgres-data-volume:/var/lib/postgresql/data

  ################################################################################
  ##                               RabbitMQ
  ################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
        - 5672:5672   # The broker
        - 15672:15672 # Web UI

  ################################################################################
  ##                               Lavalink
  ################################################################################
  lavalink:
    image: fredboat/lavalink:master
    restart: always
    ports:
        - 2333:2333
    volumes:
        - lavalink_logs:/opt/Lavalink/logs
    configs:
        - source: lavalink_yml
          target: /opt/Lavalink/application.yaml
          mode: 0644
    entrypoint: java -Xmx128m -jar Lavalink.jar

  ################################################################################
  ##                               Sentinel
  ################################################################################
  sentinel:
    image: fredboat/sentinel:dev
    restart: on-failure:3
    depends_on:
        - rabbitmq
    secrets:
        - source: fredboat_secret
          target: /opt/sentinel/common.yml
          mode: 0644
    volumes:
        - sentinel_logs:/opt/sentinel/logs
    environment:
        - "SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq"
    # Need a bigger memory size or any other custom JVM args? Uncomment and edit the line below accordingly
    # entrypoint: java -Xmx512m -jar sentinel.jar

  ################################################################################
  ##                     Quarterdeck (Database Backend)
  ################################################################################
  quarterdeck:
    image: fredboat/quarterdeck:stable-v1
    restart: always
    depends_on:
        - db
    ports:
        - 4269:4269
    configs:
        - source: quarterdeck_yml
          target: /opt/Quarterdeck/quarterdeck.yaml
          mode: 0644
    volumes:
        - quarterdeck_logs:/opt/Quarterdeck/logs

    # Need a bigger memory size or any other custom JVM args? Edit the list below accordingly
    entrypoint:
        - java
        - -Xmx128m
        - -jar
        - Quarterdeck.jar
        - >
          --spring.application.json={"security": {"admins": [{"name": "docker", "pass": "docker"}]}}

  ################################################################################
  ##                               FredBoat
  ################################################################################
  bot:
    image: fredboat/fredboat:sentinel-v3
    restart: on-failure:3
    depends_on:
        - quarterdeck
        - sentinel
        - lavalink
    secrets:
        - source: fredboat_secret
          target: /opt/FredBoat/common.yml
          mode: 0644
        - source: fredboat_yml
          target: /opt/FredBoat/fredboat.yml
          mode: 0644
    ports:
        - 1356:1356
    environment:
        - "SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq"
    volumes:
        - fredboat_logs:/opt/FredBoat/logs
      # - ./music_persistence:/opt/FredBoat/music_persistence   # Need a bigger memory size or any other custom JVM args? uncomment and edit the line below accordingly
    #entrypoint: java -Xmx256m -jar FredBoat.jar
volumes:
    postgres-data-volume:
    lavalink_logs:
    sentinel_logs:
    quarterdeck_logs:
    fredboat_logs:

configs:
    lavalink_yml:
        external: true
    quarterdeck_yml:
        external: true

secrets:
    fredboat_secret:
        external: true
    fredboat_yml:
        external: true
